### ISSUE TITLE
Cookiecutter crashing when pip-compile is not found

### ISSUE THREAD

**Issue by Ge0** [vivienm/template-python#1]
```
Select project_doc:
1 - sphinx
2 - none
Choose from 1, 2 [1]: 1
Traceback (most recent call last):
  File "/tmp/tmpipbys556.py", line 41, in <module>
    pip_compile()
  File "/tmp/tmpipbys556.py", line 34, in pip_compile
    ], stdout=DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip-compile': 'pip-compile'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```
Is it cookiecutter related?

**Comment by Ge0** [comment]
My bad, I just forgot to `pip install -r requirements.txt`.
